[tool.poetry]
name = "tool-libeep"
version = "0.1.0"
description = ""
authors = ["Steffen Heimes <sheimes@ant-neuro.com>"]
readme = "README.md"

packages = [
    { include = "libeep", from = "python" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.build]
script = "build.py"
generate-setup-file = true

[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"

[build-system]
# 1.5.2 required for https://github.com/python-poetry/poetry/issues/7505
requires = ['setuptools>=65.4.1', 'wheel', 'cmake>=3.29.2' , "poetry-core>=1.5.2"]
build-backend = "poetry.core.masonry.api"
