[project]
name = "libeep"
version = "0.1.0"
description = ""
authors = [{ name = "Steffen Heimes", email = "sheimes@ant-neuro.com" },
           { name = "Robert Smies", email = "rsmies@ant-neuro.com" },
           { name = "Velko Christoph", email = "vhristov@ant-neuro.com" }]

readme = "README.md"

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov[all]"
]

[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']
